# Generated by Django 5.2.4 on 2026-07-16 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('PAUSED', 'Pausada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meta de ahorro',
                'verbose_name_plural': 'metas de ahorro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAW', 'Retiro'), ('ADJUSTMENT', 'Ajuste')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='savings.savinggoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de ahorro',
                'verbose_name_plural': 'movimientos de ahorro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingGoalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='savings.savinggoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participante de meta',
                'verbose_name_plural': 'participantes de meta',
                'unique_together': {('goal', 'user')},
            },
        ),
    ]
