# Generated by Django 5.2.4 on 2026-07-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='compartido',
            field=models.BooleanField(default=False),
        ),
    ]
